---
  - name: Reload systemd
    ansible.builtin.systemd:
      name: keepalived-exporter
      state: restarted
      daemon_reload: yes   

  - name: Restart Keepalived Exporter
    ansible.builtin.service:
      name: keepalived-exporter
      state: restarted
