---
  - name: Apt-get update
    ansible.builtin.apt:
      update-cache: yes
      
  - name: Install Nginx
    ansible.builtin.apt:
      name: nginx

  - name: Replace index.html
    ansible.builtin.copy:
      src: files/index.html
      dest: /var/www/html/index.nginx-debian.html
    notify: Restart Nginx
    
  - name: Replace default file
    ansible.builtin.copy:
      src: files/default
      dest: /etc/nginx/sites-enabled/default
    notify: Restart Nginx    
    
  - name: Check Nginx is started and enabled
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
