---
  - name: Install Nginx
    ansible.builtin.apt:
      name: nginx

  - name: Replace index.html
    ansible.builtin.copy:
      src: index.html
      dest: /var/www/html/index.nginx-debian.html
    notify: Restart Nginx
    
  - name: Replace default file
    ansible.builtin.template:
      src: default.j2
      dest: /etc/nginx/sites-enabled/default
    notify: Restart Nginx    
       
  - name: Check Nginx is started and enabled
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
