---      
  - name: Add Influxdb Exporter service script
    ansible.builtin.get_url:
      url: "https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64"
      dest: /usr/local/bin/prometheus-influxdb-stats-exporter
      mode: 0755

  - name: Add Influxdb Exporter service
    ansible.builtin.template:
      src: prometheus-influxdb-stats-exporter.service.j2
      dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
      mode: 0755
    notify: 
      - Reload systemd

  - name: Check Influxdb Exporter is started and enabled
    ansible.builtin.service:
      name: prometheus-influxdb-stats-exporter
      state: started
      enabled: yes
