---
  - name: Reload systemd
    ansible.builtin.systemd:
      daemon_reload: yes   

  - name: Restart Influxdb Exporter
    ansible.builtin.service:
      name: prometheus-influxdb-stats-exporter
      state: restarted
