---
  - name: Add grafana key to APT
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
    
  - name: Add grafana repository to APT
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/enterprise/deb stable main

  - name: Install Grafana
    ansible.builtin.apt:
      name: grafana
      
  - name: Reverse proxy for grafana
    ansible.builtin.template:
      src: grafana.ini.j2
      dest: /etc/grafana/grafana.ini
    notify: Restart Grafana

  - name: Check Grafana is started and enabled
    ansible.builtin.service:
      name: grafana-server
      state: started
      enabled: yes
    notify: 
      - Restart Grafana
      - Change def pass
      
  - name: Datasource config for grafana
    ansible.builtin.template:
      src: datasource_config.yaml.j2
      dest: /etc/grafana/provisioning/datasources/config.yaml
    notify: Restart Grafana

  - name: Create a dashboards directory if it does not exist
    ansible.builtin.file:
      path: /var/lib/grafana/dashboards
      state: directory

  - name: Main dashboard file
    ansible.builtin.copy:
      src: main.json
      dest: /var/lib/grafana/dashboards/cluster.json
    notify: Restart Grafana

  - name: Syslog dashboard file
    ansible.builtin.copy:
      src: syslog.json
      dest: /var/lib/grafana/dashboards/syslog.json
    notify: Restart Grafana
    
  - name: Dashboard config for grafana
    ansible.builtin.template:
      src: dashboards_config.yaml.j2
      dest: /etc/grafana/provisioning/dashboards/default.yaml
    notify: Restart Grafana
    


