---
  - name: Create a grafana dirs
    ansible.builtin.file:
      recurse: yes 
      state: directory
      path: "{{ item }}"
    loop:
      - /opt/grafana/provisioning/datasources/
      - /opt/grafana/provisioning/dashboards/
            
  - name: Grafana config files
    ansible.builtin.template:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
    loop:
      - { src: 'grafana.ini.j2', dest: '/opt/grafana/grafana.ini' }
      - { src: 'datasource_config.yaml.j2', dest: '/opt/grafana/provisioning/datasources/config.yaml' }
      - { src: 'dashboards_container.yaml.j2', dest: '/opt/grafana/provisioning/dashboards/default.yaml' }
      - { src: 'main.json', dest: '/opt/grafana/provisioning/dashboards/cluster.json' }
      - { src: 'mysql.json', dest: '/opt/grafana/provisioning/dashboards/mysql.json' }
      - { src: 'syslog.json', dest: '/opt/grafana/provisioning/dashboards/syslog.json' }
    notify: Restart Docker Container
    no_log: true
    
  - name: Grafana docker container
    community.docker.docker_container:
      name: grafana
      image: grafana/grafana
      container_default_behavior: no_defaults
      published_ports: "{{ grafana_port }}:3000"
      restart_policy: always
      volumes: /opt/grafana:/etc/grafana
      state: started



