---
  - name: Install Uwsgi
    ansible.builtin.apt:
      name: uwsgi
      
  - name: Install Uwsgi python plugin
    ansible.builtin.apt:
      name: uwsgi-plugin-python3

  - name: Check Uwsgi is started and enabled
    ansible.builtin.service:
      name: uwsgi
      state: started
      enabled: yes
         
  - name: Add agama.ini
    ansible.builtin.template:
      src: agama.ini.j2
      dest: /etc/uwsgi/apps-enabled/agama.ini
    notify: Restart Uwsgi

