---
  - name: Install Uwsgi and python plugin for it
    ansible.builtin.apt:
      name: 
       - uwsgi
       - uwsgi-plugin-python3

  - name: Check Uwsgi is started and enabled
    ansible.builtin.service:
      name: uwsgi
      state: started
      enabled: yes
         
#  - name: Add agama.ini
#    ansible.builtin.template:
#      src: agama.ini.j2
#      dest: /etc/uwsgi/apps-enabled/agama.ini
#    notify: Restart Uwsgi

