---
  - name: Init
    hosts: all
    become: yes
    gather_facts: yes
    tasks:
      - setup:
    roles:
      - init
      
  - name: Node Exporter
    hosts: all
    become: yes
    roles:
      - node_exporter
      
      
  - name: Prometheus
    hosts: prometheus_servers
    become: yes
    roles:
      - prometheus
