---
  - name: Reload systemd
    ansible.builtin.systemd:
      name: pinger
      state: restarted
      daemon_reload: yes   

  - name: Restart Pinger
    ansible.builtin.service:
      name: pinger
      state: restarted
