---
  - name: Add User Agama
    ansible.builtin.user:
      name: agama
      system: yes
      
  - name: Create directory for Agama
    ansible.builtin.file:
      path: /opt/agama
      state: directory
      owner: agama
      
  - name: Install Python
    ansible.builtin.apt:
      name: python3
      
  - name: Install Flask
    ansible.builtin.apt:
      name: python3-flask
      
  - name: Install Flask-SqlAlchemy and MySql
    ansible.builtin.apt:
      name: 
       - python3-flask-sqlalchemy
       - python3-pymysql
           
  - name: Install Agama
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
      dest: /opt/agama/agama.py
