---
  - name: Create directory for Agama
    ansible.builtin.file:
      path: /opt/agama
      state: directory
          
  - name: Download agama image file
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
      dest: /opt/agama/Dockerfile

  - name: Build an Agama image
    community.docker.docker_image:
      name: agama
      source: build
      build:
        path: /opt/agama
        
  - name: Create Agama docker container
    community.docker.docker_container:
      name: agama
      image: agama
      container_default_behavior: no_defaults
      published_ports: "{{ agama_port }}:8000"
      restart_policy: always
      env:
        AGAMA_DATABASE_URI=mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_master }}/{{ mysql_database }}
    no_log: true
