---
  - name: Add User Agama
    ansible.builtin.user:
      name: agama
      system: yes
      
  - name: Create directory for Agama
    ansible.builtin.file:
      path: /opt/agama
      state: directory
      owner: agama
      
  - name: Install Python with Flask, Flask-SqlAlchemy and PyMySql
    ansible.builtin.apt:
      name: 
       - python3
       - python3-flask
       - python3-flask-sqlalchemy
       - python3-pymysql
          
  - name: Install Agama
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
      dest: /opt/agama/agama.py
