---
  - name: Create directory for Agama
    ansible.builtin.file:
      path: /opt/agama
      state: directory
      
  - name: Download file
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
      dest: /opt/agama/Dockerfile

  - name: Build an Agama image
    community.docker.docker_image:
      name: agama
      source: build
      build:
        path: /opt/agama
        
  - name: Agama docker container
    community.docker.docker_container:
      name: agama
      image: agama
      container_default_behavior: no_defaults
      published_ports: "{{ agama_port }}:8000"
      env:
<<<<<<< HEAD
        AGAMA_DATABASE_URI=mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@mysql_master/{{ mysql_database }}
    no_log: true
=======
        AGAMA_DATABASE_URI=mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_source_host }}/{{ mysql_database }}
>>>>>>> f2b55a81e512848205f8993d4f39d038901bb1d6
