---
  - name: Create a backup directory if it does not exist
    ansible.builtin.file:
      path: /home/backup/influxdb
      state: directory
      owner: 'backup'
      mode: 0700
      
  - name: Config for CronTab
    ansible.builtin.template:
      src: cron.j2
      dest: /etc/cron.d/influxdb-backup
      
      


      

