---
  - name: Add User Pinger
    ansible.builtin.user:
      name: pinger
      system: yes
      
  - name: Install fping
    ansible.builtin.apt:
      name: fping
      
  - name: Add pinger service script
    ansible.builtin.template:
      src: pinger.sh.j2
      dest: /usr/local/bin/pinger
      mode: 0755

  - name: Add pinger service
    ansible.builtin.template:
      src: pinger.service.j2
      dest: /etc/systemd/system/pinger.service
      mode: 0755
    notify: Reload systemd

  - name: Check Pinger is started and enabled
    ansible.builtin.service:
      name: pinger
      state: started
      enabled: yes
      
  - name: Create a dashboards directory if it does not exist
    ansible.builtin.file:
      path: /etc/pinger/
      state: directory
      mode: 0755
 
  - name: Add pinger service config
    ansible.builtin.template:
      src: pinger.conf.j2
      dest: /etc/pinger/pinger.conf
      mode: 0755
    notify: Restart Pinger

