---
   - name: Restart Telegraf
     ansible.builtin.service:
      name: telegraf
      state: restarted
      
   - name: Restart InfluxDB
     ansible.builtin.service:
      name: influxdb
      state: restarted

