---
   - name: Restart MySql
     ansible.builtin.service:
      name: mysql
      state: restarted
      
   - name: Reset MySQL source
     community.mysql.mysql_replication:
       mode: "{{ item }}"
       login_unix_socket: /var/run/mysqld/mysqld.sock
     loop:
       - stopreplica
       - resetprimary
     when: inventory_hostname == mysql_source_host

   - name: Reset MySQL replica
     community.mysql.mysql_replication:
       mode: "{{ item }}"
<<<<<<< HEAD
       primary_host: "mysqL_master"
=======
       primary_host: "{{ mysql_source_host }}"
>>>>>>> f2b55a81e512848205f8993d4f39d038901bb1d6
       primary_user: "{{ mysql_replication_user }}"
       primary_password: "{{ mysql_replication_password }}"
       login_unix_socket: /var/run/mysqld/mysqld.sock
     loop:
       - stopreplica
       - changeprimary
       - resetreplica
       - startreplica
     when: inventory_hostname != mysql_source_host
<<<<<<< HEAD
     no_log: true
=======
>>>>>>> f2b55a81e512848205f8993d4f39d038901bb1d6
       
